# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
]
[[override]]
  name = "github.com/containers-ai/alameda"
  branch = "master"

[[override]]
  name = "k8s.io/code-generator"
  # version for tag "kubernetes-1.16.3"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "30be4d16710ac61bce31eb28a01054596fe6a9f1"

[[override]]
  name = "github.com/go-openapi/spec"
  branch = "master"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  version = "=v0.2.3"

[[override]]
  name = "k8s.io/api"
  # version for tag "kubernetes-1.16.3"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # version for tag "kubernetes-1.16.3"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/apimachinery"
  # version for tag "kubernetes-1.16.3"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/client-go"
  # version for tag "kubernetes-1.16.3"
  version = "kubernetes-1.16.3"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.34.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.4.0"

[[override]]
  name = "k8s.io/kube-aggregator"
  # version for tag "kubernetes-1.16.3"
  version = "kubernetes-1.16.3"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master" #osdk_branch_annotation
  # version = "=v0.5.0" #osdk_version_annotation

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false

  [[prune.project]]
    name = "github.com/containers-ai/alameda"
    non-go = false
    unused-packages = true

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "k8s.io/kube-aggregator"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[[constraint]]
  branch = "master"
  name = "github.com/influxdata/influxdb1-client"
